1.7.0
vatsimnetwork/nattrak pull request #127
Opened 2024-04-04 23:39 UTC by lieselwd

- Changes to oceanic clearance procedures (#126)
- Allow for manual creation of a CLX

2024-07-06 22:50 UTC, Verbjimtim approved these changes

2024-08-28 22:06 UTC, williammck requested changes

2024-09-02 04:44 UTC, lieselwd commented on app/Http/Requests/RclMessageRequest.php
> +                        if (config('app.rcl_auto_acknowledgement_enabled')) {
That one I can't actually remember at all, I'll comment it out for now and investigate

2024-09-02 04:49 UTC, lieselwd commented on app/Http/Requests/RclMessageRequest.php
> +                        $validator->errors()->add('entry_time.range', 'You are either too early or too late to submit oceanic clearance. If you are entering the oceanic more than 90 minutes from now,
Added

2024-09-02 04:58 UTC, williammck approved these changes

2024-09-02 04:58 UTC, merged